version: "3.9"
services:
  forward-proxy:
    image: "hinata/nginx-forward-proxy:latest"
    ports:
      - "3128:3128"
    volumes:
      - ~/Docker/Data/proxy/nginx.conf:/usr/local/nginx/conf/nginx.conf

